language: python
python: 3.9

services:
  - docker

install:
  - 'pip install poetry'
  - 'poetry install'

script:
  - poetry run pre-commit run --all-files
  - poetry run pytest

before_deploy:
  # Checking out the branch is necessary because Travis operates in a
  # "detached HEAD" state. This breaks git-based inspection of current
  # branch, which is used in the following "version" logic
  - git checkout $TRAVIS_BRANCH
  - SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa) ./scripts/build.sh

