name: yield_estimation
channels:
  - conda-forge
dependencies:
  - python=3.9
  # dev dependencies
  - pytest
  - pre_commit
  - sphinx
  - sphinx_rtd_theme
  # main dependencies
  - click
  - arrow
  # subpackage dependencies
  # private dependencies
#  - pip:
#    - git+ssh://git@github.com/SenteraLLC/some-py-repo
